<a href="https://colab.research.google.com/github/ksenera/jupyter_notebooks/blob/main/Assignment1_ksenera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from pandas import read_csv
filename = "/content/drive/MyDrive/pima-indians-diabetes.data.csv"
featureNames = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
myData = read_csv(filename, names= featureNames)
peek = myData.head(5)
print(peek)

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1


In [ ]:
correlations = myData.corr(method='pearson')
print(correlations)

           preg      plas      pres      skin      test      mass      pedi  \
preg   1.000000  0.129459  0.141282 -0.081672 -0.073535  0.017683 -0.033523   
plas   0.129459  1.000000  0.152590  0.057328  0.331357  0.221071  0.137337   
pres   0.141282  0.152590  1.000000  0.207371  0.088933  0.281805  0.041265   
skin  -0.081672  0.057328  0.207371  1.000000  0.436783  0.392573  0.183928   
test  -0.073535  0.331357  0.088933  0.436783  1.000000  0.197859  0.185071   
mass   0.017683  0.221071  0.281805  0.392573  0.197859  1.000000  0.140647   
pedi  -0.033523  0.137337  0.041265  0.183928  0.185071  0.140647  1.000000   
age    0.544341  0.263514  0.239528 -0.113970 -0.042163  0.036242  0.033561   
class  0.221898  0.466581  0.065068  0.074752  0.130548  0.292695  0.173844   

            age     class  
preg   0.544341  0.221898  
plas   0.263514  0.466581  
pres   0.239528  0.065068  
skin  -0.113970  0.074752  
test  -0.042163  0.130548  
mass   0.036242  0.292695  
pedi   0.0335

In [ ]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
array = myData.values
X = array[:,0:8]
Y = array[:,8:]
scaler = MinMaxScaler(feature_range=(0, 1))
scaledX = scaler.fit_transform(X)
set_printoptions(precision=3)
print(scaledX[0:5,:])


[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


In [ ]:
rescaleddataframe = pd.DataFrame(scaledX, columns=featureNames[0:8])
rescaledcorr = rescaleddataframe.corr(method='pearson')
print(rescaledcorr)

          preg      plas      pres      skin      test      mass      pedi  \
preg  1.000000  0.129459  0.141282 -0.081672 -0.073535  0.017683 -0.033523   
plas  0.129459  1.000000  0.152590  0.057328  0.331357  0.221071  0.137337   
pres  0.141282  0.152590  1.000000  0.207371  0.088933  0.281805  0.041265   
skin -0.081672  0.057328  0.207371  1.000000  0.436783  0.392573  0.183928   
test -0.073535  0.331357  0.088933  0.436783  1.000000  0.197859  0.185071   
mass  0.017683  0.221071  0.281805  0.392573  0.197859  1.000000  0.140647   
pedi -0.033523  0.137337  0.041265  0.183928  0.185071  0.140647  1.000000   
age   0.544341  0.263514  0.239528 -0.113970 -0.042163  0.036242  0.033561   

           age  
preg  0.544341  
plas  0.263514  
pres  0.239528  
skin -0.113970  
test -0.042163  
mass  0.036242  
pedi  0.033561  
age   1.000000  


The correlations in the rescaled data have not changed compared to the original correlations. However class is not included in features.

In [ ]:
classgroup = myData.groupby('class')
print(classgroup.size())

class
0    500
1    268
dtype: int64


In [ ]:
class_0 = classgroup.get_group(0)
class0corr = class_0.corr(method='pearson')
print(class0corr)

           preg      plas      pres      skin      test      mass      pedi  \
preg   1.000000  0.098685  0.133096 -0.118340 -0.131986  0.016495 -0.079951   
plas   0.098685  1.000000  0.192795  0.016015  0.352957  0.131749  0.095548   
pres   0.133096  0.192795  1.000000  0.187072  0.074626  0.363178  0.027292   
skin  -0.118340  0.016015  0.187072  1.000000  0.412790  0.438606  0.095181   
test  -0.131986  0.352957  0.074626  0.412790  1.000000  0.254202  0.227385   
mass   0.016495  0.131749  0.363178  0.438606  0.254202  1.000000  0.070664   
pedi  -0.079951  0.095548  0.027292  0.095181  0.227385  0.070664  1.000000   
age    0.572776  0.228018  0.214694 -0.163788 -0.149234  0.036070  0.041665   
class       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

            age  class  
preg   0.572776    NaN  
plas   0.228018    NaN  
pres   0.214694    NaN  
skin  -0.163788    NaN  
test  -0.149234    NaN  
mass   0.036070    NaN  
pedi   0.041665    NaN  
age    1.

Yes the correlations are still equal to assignment task 3 as per document.

In [ ]:
class_1 = classgroup.get_group(1)
class1corr = class_1.corr(method='pearson')
print(class1corr)

           preg      plas      pres      skin      test      mass      pedi  \
preg   1.000000 -0.054591  0.126963 -0.079165 -0.078563 -0.159071 -0.069195   
plas  -0.054591  1.000000  0.068699  0.037618  0.261368  0.050418  0.026474   
pres   0.126963  0.068699  1.000000  0.225247  0.089367  0.133951  0.034522   
skin  -0.079165  0.037618  0.225247  1.000000  0.456558  0.312058  0.273900   
test  -0.078563  0.261368  0.089367  0.456558  1.000000  0.055112  0.101565   
mass  -0.159071  0.050418  0.133951  0.312058  0.055112  1.000000  0.136761   
pedi  -0.069195  0.026474  0.034522  0.273900  0.101565  0.136761  1.000000   
age    0.444987  0.098565  0.262684 -0.092012  0.023944 -0.188012 -0.088119   
class       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

            age  class  
preg   0.444987    NaN  
plas   0.098565    NaN  
pres   0.262684    NaN  
skin  -0.092012    NaN  
test   0.023944    NaN  
mass  -0.188012    NaN  
pedi  -0.088119    NaN  
age    1.

The correlations between class 0 and class 1 are not the same as there was bound to be differences between individuals with diabetes and those without.